version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
  unit_tests:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:sdk
    override:
      - dotnet test
    steps:
      - run: dotnet restore
      - run: dotnet test /temp/unit/Application.Core.Tests/Application.Core.Tests.csproj
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit_tests:
          requires:
            - build