version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
  unit_tests:
    steps:
      - run: dotnet test
workflows:
  version: 2
  build-unit-test:
    jobs:
      - build
      - unit-test:
          requires:
            - build