version: '2'

services:  
  webui:
    image: ftm    
    container_name: ftm-test
    build:
      context: ./src/Presentation.API
      dockerfile: Dockerfile2
      args:
        source: ./build
    ports:
      - "5000:80"