version: '2'

services:
  ftm:
    container_name: ftm
    image: petprojects/toggling-it:${BUILD_VERSION}
    build:
      context: ./src/Presentation.API
      dockerfile: Dockerfile
      args:
        source: ./build
  ci-integration-tests:
    image: microsoft/dotnet:1.1.2-sdk
    container_name: integrationtests
    volumes:
     - .:/src
    working_dir: /src
    environment:
     - ApiEndpoint=http://ftm/
    links:
     - ftm
    command: sh ./deploy/scripts/run-integration-tests.sh
